[default]
timeout=30

[gezondheidenwetenschap.be]
title = "Gezondheid en Wetenschap - Fact Checks"
url = "https://www.gezondheidenwetenschap.be/gezondheid-in-de-media"
entrySelector = "div.searchHeadline"
titleSelector = "a"
linkSelector = "a"

[cortexfutura]
title = "Cortex Futura"
url = "https://www.cortexfutura.com/articles/"
entrySelector = "article"
titleSelector = "h2 a"
linkSelector = "h2 a"

[biorxiv]
title = "bioRxiv - amyloid"
url = "https://www.biorxiv.org/search/amyloid%20jcode%3Abiorxiv%20numresults%3A75%20sort%3Apublication-date%20direction%3Adescending%20format_result%3Astandard"
entrySelector = "ul.highwire-search-results-list li"
titleSelector = "a span.highwire-cite-title"
linkSelector = "span a"

[biorxiv-afm]
title = "bioRxiv - amyloid"
url = "https://www.biorxiv.org/search/%2522atomic%252Bforce%252Bmicroscopy%2522%20numresults%3A10%75sort%3Apublication-date%20direction%3Adescending%20format_result%3Astandard"
entrySelector = "ul.highwire-search-results-list li"
titleSelector = "a span.highwire-cite-title"
linkSelector = "span a"

[markozivanovic]
title = "Marko Zivanovic"
url = "https://www.markozivanovic.com/"
entrySelector = ".post h3"
titleSelector = "a"
linkSelector = "a"

[nature]
title = "Nature - research articles"
url = "https://www.nature.com/nature/research-articles"
entrySelector = "article"
titleSelector = "a"
linkSelector = "a"

[brady-johnston]
title = "Brady Johnston"
url = "https://bradyajohnston.github.io"
entrySelector = "div.card-body.post-contents"
titleSelector = "h5"
linkSelector = "h5"

[zimmo]
title = "Zimmo"
url = "https://www.zimmo.be/nl/zoeken/?search=eyJmaWx0ZXIiOnsic3RhdHVzIjp7ImluIjpbIlRPX1JFTlQiXX0sInByaWNlIjp7InVua25vd24iOnRydWUsInJhbmdlIjp7Im1pbiI6OTAwLCJtYXgiOjE1MDB9fSwiY2F0ZWdvcnkiOnsiaW4iOlsiSE9VU0UiLCJBUEFSVE1FTlQiXX0sInBsYWNlSWQiOnsiaW4iOlsyMjZdfX0sInBhZ2luZyI6eyJmcm9tIjowLCJzaXplIjoxOX0sInNvcnRpbmciOlt7InR5cGUiOiJEQVRFIiwib3JkZXIiOiJERVNDIn1dfQ%3D%3D&p=1#gallery"
entrySelector = ".property-item"
titleSelector = ".property-item_address"
linkselector = "a"
