[default]
timeout=30

[cortexfutura]
title = "Cortex Futura"
url = "https://www.cortexfutura.com/articles/"
entrySelector = "article"
titleSelector = "h2 a"
linkSelector = "h2 a"

[biorxiv]
title = "bioRxiv - amyloid"
url = "https://www.biorxiv.org/search/amyloid%252BOR%252B%2522inclusion%252Bbody%2522%252BOR%252B%2522amorphous%252Baggregate%2522%20numresults%3A10%20sort%3Apublication-date%20direction%3Adescending"
entrySelector = "ul.highwire-search-results-list li"
titleSelector = "a span.highwire-cite-title"
linkSelector = "span a"

[markozivanovic]
title = "Marko Zivanovic"
url = "https://www.markozivanovic.com/"
entrySelector = ".post h3"
titleSelector = "a"
linkSelector = "a"

[nature]
title = "Nature - research articles"
url = "https://www.nature.com/nature/research-articles"
entrySelector = "article"
titleSelector = "a"
linkSelector = "a"
